version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "myfun"
        Alias: "LambdaFunctionAlias"
        CurrentVersion: "1"
        TargetVersion: "2"
